### ISSUE TITLE
Add note to README.md about running OpenGL extension for xpra

### ISSUE THREAD

**Issue by HoshiYamazaki** [kaueraal/run_scaled#18]
If you run Arch, you need:
https://aur.archlinux.org/packages/python2-opengl-accelerate/
Or (and?):
https://aur.archlinux.org/packages/python-opengl-accelerate/

**Comment by kaueraal** [comment]
This is the wrong project for this, as it's a dependency of xpra. Said packages should be a dependency of the xpra package, not of this one.
