### ISSUE TITLE
Blurry image

### ISSUE THREAD

**Issue by zezic** [kaueraal/run_scaled#2]
Script works just fine but I can't get rid of xpra "antialiasing". I want just crisp 2x scaling without texture filter.
Can you give any hints on this?

**Comment by kaueraal** [comment]
Unfortunately xpra doesn't seem to support it and the xserver itself also. You could open a feature request in xpra, but I don't think they will support it, as they use simple opengl scaling. If they implement it I'll add a flag for enabling this scaling mode.

**Comment by zezic** [comment]
I got it by modifying xpra sources and replacing some `GL_LINEAR` with `GL_NEAREST` and also by disabling one condition.
But, anyway, xpra can't give me necessary framerate (i'm work with Renoise).
But, anyway, thank you for such useful script =)

**Comment by kaueraal** [comment]
If it's so easy the folks of xpra probably appreciate that patch/feature request. But yeah, for applications like renoise it is too sluggish with xpra.

**Comment by ihewitt** [comment]
@zezic I'm trying to achieve the same, but having changed the GL_LINEARs and tried to remove some of the scaling logic, I'm still getting smoothing, can you share your changes?

**Comment by zezic** [comment]
@ihewitt Sorry, but it seems like I deleted xpra sources from my machine.
I tryed to download sources and replay my thoughts from Apr 23, so, may be this diff can help you:
```diff
zezic@UX305FA:~/Documents/Soft/Utils$ colordiff -r xpra-2.1.3-orig xpra-2.1.3
diff -r xpra-2.1.3-orig/xpra/client/gl/gl_window_backing_base.py xpra-2.1.3/xpra/client/gl/gl_window_backing_base.py
671,672c671,672
<             glTexParameteri(target, GL_TEXTURE_MAG_FILTER, GL_LINEAR)
<             glTexParameteri(target, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
---
>             glTexParameteri(target, GL_TEXTURE_MAG_FILTER, GL_NEAREST)
>             glTexParameteri(target, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
1083,1084c1083,1084
<                 if scaling or (div_w > 1 or div_h > 1):
<                     mag_filter = GL_LINEAR
---
>                 # if scaling or (div_w > 1 or div_h > 1):
>                 #     mag_filter = GL_LINEAR
```

**Comment by ihewitt** [comment]
thanks, hmm ok I already did that but still get smoothing on scaling up. I'll take this over to the xpra project to discuss.
