### ISSUE TITLE
Stopped working suddenly on Ubuntu 18.04

### ISSUE THREAD

**Issue by snhirsch** [kaueraal/run_scaled#21]
Was working fine until about 3 days ago, when this started happening:

`hirsch@z87:~$ bash -x run_scaled xv
+ SCALING_FACTOR=2
+ USE_OPENGL=no
+ SLEEPTIME=1
+ PERFORMANCE_OPTIONS='--encoding=rgb --mmap=yes --compress=0'
+ '[' 1 = 0 ']'
+ true
+ '[' 1 -gt 0 ']'
+ case $1 in
+ break
+ declare -i UNSCALED_RESOLUTION_X
+ declare -i UNSCALED_RESOLUTION_Y
++ xrandr
++ sed -n -e 's/Screen 0:.*current \([0-9]\+\) x \([0-9]\+\).*/\1/p'
+ UNSCALED_RESOLUTION_X=3840
++ xrandr
++ sed -n -e 's/Screen 0:.*current \([0-9]\+\) x \([0-9]\+\).*/\2/p'
+ UNSCALED_RESOLUTION_Y=2160
++ bc
++ bc
+ UNSCALED_RESOLUTION=1920x1080
++ shuf -i 10000-99999999 -n 1
+ DISPLAYNUM=:10837945
++ printf '%q ' xv
+ ESCAPED_PARAMS='xv '
+ xpra start :10837945 '--xvfb=Xvfb +extension Composite -screen 0 1920x1080x24+32 -nolisten tcp -noreset  -auth $XAUTHORITY' --env=GDK_SCALE=1 --env=GDK_DPI_SCALE=1 '--start-child=xv ' --exit-with-children
using systemd-run to wrap 'start' server command
'systemd-run' '--description' 'xpra-start' '--scope' '--user' '/usr/bin/xpra' 'start' ':10837945' '--xvfb=Xvfb +extension Composite -screen 0 1920x1080x24+32 -nolisten tcp -noreset  -auth $XAUTHORITY' '--env=GDK_SCALE=1' '--env=GDK_DPI_SCALE=1' '--start-child=xv ' '--exit-with-children=yes' '--systemd-run=no'
Job for run-rbde5af5f795a4f6ca2ad1953aa3f121e.scope failed.
See "systemctl status run-rbde5af5f795a4f6ca2ad1953aa3f121e.scope" and "journalctl -xe" for details.
+ sleep 1
+ xpra attach :10837945 --desktop-scaling=2 --opengl=no --encoding=rgb --mmap=yes --compress=0
2019-01-19 10:34:39,445 Xpra gtk2 client version 2.5-r21174 64-bit
2019-01-19 10:34:39,446  running on Linux Ubuntu 18.04 bionic
2019-01-19 10:34:39,447  window manager is 'KWin'
2019-01-19 10:34:40,155 GStreamer version 1.14.1 for Python 2.7.15 64-bit
xpra initialization error:
 cannot find live server for display :10837945
+ xpra stop :10837945
xpra initialization error:
 cannot find live server for display :10837945
`
Only the second recommended diagnostic returns a meaningful answer:

`Jan 19 10:34:37 z87 polkitd(authority=local)[536]: Registered Authentication Agent for unix-process:12152:240225392 (system bus name :1.1502
Jan 19 10:34:37 z87 systemd[1612]: run-rbde5af5f795a4f6ca2ad1953aa3f121e.scope: Failed to add PIDs to scope's control group: Permission deni
Jan 19 10:34:37 z87 systemd[1612]: run-rbde5af5f795a4f6ca2ad1953aa3f121e.scope: Failed with result 'resources'.
Jan 19 10:34:37 z87 systemd[1612]: Failed to start xpra-start.
-`

Any suggestions?

**Comment by totaam** [comment]
`--systemd-run=no`

**Comment by sopgenorth** [comment]
I was able to fix this by installing xpra from the official site, instead of from the default Ubuntu sources. They don't have fantastic instructions though: https://xpra.org/trac/wiki/Download#Linux

**Comment by snhirsch** [comment]
It's baaackk...  Out of the blue, run_scaled is crashing again on Ubuntu 18.04.  I have the --systemd-run=no specified.  Please let me know what you might need to debug?

**Comment by kaueraal** [comment]
Xpra directly includes an equivalent tool since [version 4.1](https://github.com/Xpra-org/xpra/blob/4d73c3644d6692bd51376296ed913f18a809f1a9/docs/CHANGELOG.md#41-2021-02-26). It is also called `run_scaled` and is part of [the default Xpra installation](https://github.com/Xpra-org/xpra/blob/master/fs/bin/run_scaled).

Hence, this script here is deprecated and no longer maintained. I'm sorry that it took me quite long to officially announce it here. Thank you for your support and please continue your HiDPI journey with Xpra's tool!
