### ISSUE TITLE
script re-written and packaged in xpra

### ISSUE THREAD

**Issue by totaam** [kaueraal/run_scaled#36]
Thank you for the inspiration.
As part of an effort to make xpra more user-friendly, I have re-written the `run_scaled` script and will be packaging it in xpra 4.1. (including a man page, etc)

Please see [xpra ticket 2813 : bundle a better run_scaled](http://xpra.org/trac/ticket/2813#comment:1)

Please let me know what copyright should be applied to this script since it is largely inspired by your version.

**Comment by cspeterson** [comment]
Looking forward to seeing your rewrite when it comes with your xpra packages!

re license: https://github.com/kaueraal/run_scaled/blob/master/LICENSE

**Comment by totaam** [comment]
Would you be OK with the new script being GPL2+ instead?
(would make my life easier when packaging things to limit the number of licenses we carry)

**Comment by kaueraal** [comment]
The 3 clause BSD license is compatible with the GPL2+ license, so I'd say just put it under the general license xpra is under.

I'm glad to see you'll include an very improved version of this script. Thanks for the work!

**Comment by totaam** [comment]
And now we've also moved to github, so the issue is here:
https://github.com/Xpra-org/xpra/issues/2813
