### ISSUE TITLE
Fractional Scaling: Syntax

### ISSUE THREAD

**Issue by rendsvig** [kaueraal/run_scaled#6]
Hi! Thank you for the great work!

Concerning fractional scaling, then what syntax should one use? In particular, say I want a 10% or 20% increase in size, then how would I obtain that?

I can get a ~50% increase by `--scale=1/2`, but other fractional values behave erratically.

Kind regards,

**Comment by kaueraal** [comment]
Use e.g. `--scale=1.2` for a 20% increase.

**Comment by rendsvig** [comment]
I swear I had tried that, but got an error concerning an invalid arithmetic operation, which I'm now unable to reproduce.
But thank you!
